### ISSUE TITLE
School Management System

### ISSUE THREAD

**Issue by nishanthss04** [nishanthss04/my-collection#1]
- Description: This project creates a database that can be used to make the job of an admin very easy. The admin can use the GUI to upload all sorts of details, such as student registration, fee details, parent enquiries, teacher enquiries, and student details.

- Technologies: Python, Tkinter, MySQL.

- Features:

1. User-friendly GUI
2. Connection to MySQL database
3. Ability to upload student registration details
4. Ability to upload fee details
5. Ability to record parent enquiries
6. Ability to record teacher enquiries
7. Ability to view student details

- Installation:

1. Clone the repository
2. Install the required Python libraries
3. Create a MySQL database and user
4. Update the database connection details in the config.py file
5. Run the app.py file

- Usage:

1. The admin can use the GUI to navigate to the different features of the system.
2. To upload student registration details, the admin must enter the student's name, email address, and other relevant information.
3. To upload fee details, the admin must enter the student's ID number, fee amount, and due date.
4. To record a parent enquiry, the admin must enter the parent's name, email address, and the enquiry message.
5. To record a teacher enquiry, the admin must enter the teacher's name, email address, and the enquiry message.
6. To view student details, the admin must enter the student's ID number.

to check out the code go to the repository section
For running the exiting code:
Username : admin
password : cmrnps

**Comment by Ibrahimwatts** [comment]
why don't you apply Python frameworks when it comes to database? because absolutely you would have used Flask or Django fro purposes of database

**Comment by nishanthss04** [comment]
I wanted to use MySQL at that point of time because that was the only database that I knew how to work on it at that point of time.
